spring:
  application:
    name: frauddetection

  datasource:
    url: jdbc:postgresql://localhost:5432/frauddb
    username: frauduser
    password: fraudpass

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

fraud:
  rules:
    amount-threshold:
      threshold: 50000
      score: 40

  decision:
    approve-max-score: 30
    otp-max-score: 70